#######################################################
# 
# Account.py
# Python implementation of the Class Account
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:46
# Original author: Kolya
# 
#######################################################
from Trace.Account import Account

class Account:
    m_Account= Account()

    def add() -> var:
        pass

    def delete() -> var:
        pass

    def get() -> var:
        pass

    def update() -> var:
        pass

    def test_method() -> var:
        pass