#######################################################
# 
# AddDiet.py
# Python implementation of the Class AddDiet
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:47
# Original author: Kolya
# 
#######################################################


class AddDiet:
    def add_diet(weight : var, age : int, name : var, description : var, special : var, height : var) -> var:
        pass