#######################################################
# 
# AddDish.py
# Python implementation of the Class AddDish
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:48
# Original author: Kolya
# 
#######################################################


class AddDish:
    def add_dish(name : var, diet : var) -> var:
        pass