#######################################################
# 
# Auth.py
# Python implementation of the Class Auth
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:48
# Original author: Kolya
# 
#######################################################


class Auth:
    test: int

    def auth(login : var, password : var) -> var:
        pass

    def mehod() -> void:
        pass

    def mehod2() -> int:
        pass