#######################################################
# 
# Diet.py
# Python implementation of the Class Diet
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:49
# Original author: Kolya
# 
#######################################################
from Trace.Diet import Diet

class Diet:
    m_Diet= Diet()

    def add() -> var:
        pass

    def delete() -> var:
        pass

    def get() -> var:
        pass

    def update() -> var:
        pass