#######################################################
# 
# Dish.py
# Python implementation of the Class Dish
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:49
# Original author: Kolya
# 
#######################################################
from Trace.Dish import Dish

class Dish:
    m_Dish= Dish()

    def add() -> var:
        pass

    def delete() -> var:
        pass

    def get() -> var:
        pass

    def update() -> var:
        pass