#######################################################
# 
# FillAboutMe.py
# Python implementation of the Class FillAboutMe
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:49
# Original author: Kolya
# 
#######################################################


class FillAboutMe:
    def update_aboutme(weight : var, age : int, name : var, description : var, special : var) -> var:
        pass