#######################################################
# 
# FindDiet.py
# Python implementation of the Class FindDiet
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:49
# Original author: Kolya
# 
#######################################################


class FindDiet:
    def find_diet(login : var) -> var:
        pass