#######################################################
# 
# GetHistoryDiet.py
# Python implementation of the Class GetHistoryDiet
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:50
# Original author: Kolya
# 
#######################################################


class GetHistoryDiet:
    def get_history_diet(login : var) -> var:
        pass