#######################################################
# 
# HistoryDiet.py
# Python implementation of the Class HistoryDiet
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:50
# Original author: Kolya
# 
#######################################################
from Trace.HistoryDiet import HistoryDiet

class HistoryDiet:
    m_HistoryDiet= HistoryDiet()

    def add() -> var:
        pass

    def get() -> var:
        pass