#######################################################
# 
# RegistrationControl.py
# Python implementation of the Class RegistrationControl
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:50
# Original author: Kolya
# 
#######################################################


class RegistrationControl:
    def check(login : var, password : var) -> var:
        pass

    def save_user(login : var, password : var) -> var:
        pass