#######################################################
# 
# RestorePassword.py
# Python implementation of the Class RestorePassword
# Generated by Enterprise Architect
# Created on:      05-дек-2023 15:31:51
# Original author: Kolya
# 
#######################################################


class RestorePassword:
    def retore_password(login : var, password : var, phone : var) -> var:
        pass