/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 05-дек-2023 17:20:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "JoinДиетаToБлюда" CASCADE
;

DROP TABLE IF EXISTS "Аккаунт" CASCADE
;

DROP TABLE IF EXISTS "Блюда" CASCADE
;

DROP TABLE IF EXISTS "Диета" CASCADE
;

DROP TABLE IF EXISTS "История диет" CASCADE
;

/* Create Tables */

CREATE TABLE "JoinДиетаToБлюда"
(
	id int NULL
)
;

CREATE TABLE "Аккаунт"
(
	id int NOT NULL,
	"Вес" float NULL,
	"Возраст" int NULL,
	"Логин" char NULL,
	"Особенности" int NULL,
	"Пароль" char NULL,
	"Почта" char NULL,
	"Рост" float NULL,
	"Телефон" char NULL,
	"Тип аккаунта" enum NULL
)
;

CREATE TABLE "Блюда"
(
	id int NOT NULL,
	"Диета" int NULL,
	"Название" char NULL
)
;

CREATE TABLE "Диета"
(
	id int NOT NULL,
	"Вес" float NULL,
	"Возраст" int NULL,
	"Название" char NULL,
	"Описание" char NULL,
	"Особенности" int NULL,
	"Рост" float NULL
)
;

CREATE TABLE "История диет"
(
	"Дата начала диеты" char NULL,
	"Дата окончания диеты" char NULL,
	id int NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Аккаунт" ADD CONSTRAINT "PK_Аккаунт"
	PRIMARY KEY (id)
;

ALTER TABLE "Блюда" ADD CONSTRAINT "PK_Блюда"
	PRIMARY KEY (id)
;

ALTER TABLE "Диета" ADD CONSTRAINT "PK_Диета"
	PRIMARY KEY (id)
;

ALTER TABLE "Диета" ADD CONSTRAINT "PK_Диета"
	PRIMARY KEY (id)
;

ALTER TABLE "История диет" ADD CONSTRAINT "PK_История диет"
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE "JoinДиетаToБлюда" ADD CONSTRAINT "FK_Блюда"
	FOREIGN KEY (id) REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "JoinДиетаToБлюда" ADD CONSTRAINT "FK_Диета"
	FOREIGN KEY (id) REFERENCES "Диета" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "История диет" ADD CONSTRAINT "FK_Аккаунт_История диет"
	FOREIGN KEY (id) REFERENCES "Аккаунт" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "История диет" ADD CONSTRAINT "FK_Диета_История диет"
	FOREIGN KEY (id) REFERENCES "Диета" (id) ON DELETE No Action ON UPDATE No Action
;
