/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 01-дек-2023 16:50:56 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Аккаунт" CASCADE
;

DROP TABLE IF EXISTS "Блюда" CASCADE
;

DROP TABLE IF EXISTS "Диета" CASCADE
;

DROP TABLE IF EXISTS "История диет" CASCADE
;

/* Create Tables */

CREATE TABLE "Аккаунт"
(
	id int NULL,
	"Вес" float NULL,
	"Возраст" int NULL,
	"Логин" char NULL,
	"Особенности" int NULL,
	"Пароль" char NULL,
	"Почта" char NULL,
	"Рост" float NULL,
	"Телефон" char NULL,
	"Тип аккаунта" enum NULL
)
;

CREATE TABLE "Блюда"
(
	id int NULL,
	"Диета" int NULL,
	"Название" char NULL
)
;

CREATE TABLE "Диета"
(
	id int NULL,
	"Вес" float NULL,
	"Возраст" int NULL,
	"Название" char NULL,
	"Описание" char NULL,
	"Особенности" int NULL,
	"Рост" float NULL
)
;

CREATE TABLE "История диет"
(
	"Дата начала диеты" char NULL,
	"Дата окончания диеты" char NULL
)
;
